### ISSUE TITLE
Using Sapper: <Chart> is not a valid SSR component

### ISSUE THREAD

**Issue by spsaucier-bakkt** [himynameisdave/svelte-frappe-charts#14]
Using the example:
```
<script>
  import Chart from 'svelte-frappe-charts';

  let data = {
    labels: ['Sun', 'Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat'],
    datasets: [
      {
        values: [10, 12, 3, 9, 8, 15, 9]
      }
    ]
  };
</script>

<Chart data={data} type="line" />
```

It gives me a 500 error:
```
<Chart> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

Is there an easy fix for this? Is it possible to use SSR with this package?

**Comment by spsaucier-bakkt** [comment]
When I `yarn install -d svelte-frappe-charts` instead, it doesn't throw this error, but it renders nothing where the chart should be.

**Comment by himynameisdave** [comment]
@spsaucier-bakkt thanks for reporting. You shouldn't need a hacky workaround like installing to dev dependencies to get this working  (although I think the command for that is `yarn add -D svelte-frappe-charts`, not sure if that's what you meant).

I personally have not used this package in a SSR app, so any additional details about your build setup which you could post would be awesome (a sample repo would be even better).

Perhaps related: https://github.com/sveltejs/sapper/issues/774

**Comment by spsaucier-bakkt** [comment]
Interestingly, installing to devDependencies isn't _exactly_ a hack when it comes to svelte/sapper, since it's kind of a compiler in itself.

My setup is basically the standard sapper app.

**Comment by jrschumacher** [comment]
> When using Svelte components installed from npm, such as @sveltejs/svelte-virtual-list, Svelte needs the original component source (rather than any precompiled JavaScript that ships with the component). This allows the component to be rendered server-side, and also keeps your client-side app smaller.

https://github.com/sveltejs/sapper-template#using-external-components

**Comment by kyranis-studio** [comment]
a have the same probleme to solve it i import the module like that :
import Chart from 'svelte-frappe-charts/src/components/base.svelte';
