### ISSUE TITLE
How can I set container for frappe charts

### ISSUE THREAD

**Issue by daiqe** [himynameisdave/svelte-frappe-charts#15]
As I know frappe chart's width depends on its container. So in svelte-frappe-charts how can I control charts width through container. like <div class="container"><charts/><div/> . I try to reset div width but it seems it is not charts container. How can I set a container for frappe chart in svelte like
 const container = document.querySelector('#chart');
 const chart = new Chart(container, options)

**Comment by himynameisdave** [comment]
Currently consumers of this component have no real way to customize the charts container.

However, you can get a reference to the `Chart` element itself by adding a `bind:this` to this component:

```svelte
<script>
  // ...

  let chartRef;
</script>

<Chart data={data} type="line" bind:this={chartRef} />
```

This may allow you to set the width of that element (but I have not tested this). If not, another solution that I would like to explore is to encapsulate this component in a [`use:`](https://medium.com/better-programming/practical-svelte-the-use-directive-60635671335f) directive, which would allow the consumer full control of the element the chart is mounted to.

**Comment by himynameisdave** [comment]
Using `chartRef` should allow you to do anything you'd normally be able to do with a DOM node, including dynamically changing the width. Closing this issue, but feel free to re-open/file a new issue if you have any new info.
