### ISSUE TITLE
Options not reactive

### ISSUE THREAD

**Issue by jnordberg** [himynameisdave/svelte-frappe-charts#17]
Component does not update if you change colors or chart options

**Comment by himynameisdave** [comment]
Interesting. I'll need to explore why this isn't working as expected. [This would be a good place to start](https://github.com/himynameisdave/svelte-frappe-charts/blob/master/src/components/base.svelte#L59).

**Comment by himynameisdave** [comment]
@jnordberg while it's true that updating the `colors` prop (or other non-`data` props) does not update the chart, I believe that this is a limitation of the [`update`](https://frappe.io/charts/docs/reference/api#update) method in the `frappe-charts` library itself. I'd recommend filing an issue over there, or seeing if there is a similar one which has been filed over there (looks like it may already have been worked on: https://github.com/frappe/charts/pull/179).

Once that change lands, we will be able to make an update here to allow props such as `colors` to update the underlying chart.
