### ISSUE TITLE
colors options not working

### ISSUE THREAD

**Issue by hussamkhatib** [himynameisdave/svelte-frappe-charts#50]
eg:     colors: ['violet']  render out the default blue color chart

**Comment by himynameisdave** [comment]
Hi @hussamkhatib! 

Just tested and the `colors` does work as expected:

```svelte
<Chart
  colors={['violet']}
  data={data}
/>
```

Please try this and let me know if it works for you. If not we can re-open this issue and investigate.

**Comment by hussamkhatib** [comment]
Oh, I see it's a separate prop in the component itself.
I had been referring to the main docs and saw data object and their nested field, since data was at the top and its name signifies a generic root object, I thought all key values goes inside this object. Just realized I was wrong.
Thanks for a lot

**Comment by himynameisdave** [comment]
@hussamkhatib I can see why you were confused, I think when v2 of `frappe-charts` is released we will update our API to be a bit more clear.
